### PR TITLE
tbDEX PFI 🤝  FTL

### PR DESCRIPTION
**Pull request by KendallWeihe**
This is a large PR, apologies for that. Going to make an attempt to make it digestible here in the description, so please read carefully before proceeding.

## Why?

The elevator pitch here goes something like: Build a tbDEX PFI (by [building a HTTP API](https://github.com/TBD54566975/tbdex/tree/main/specs/http-api)), using [FTL](https://github.com/TBD54566975/ftl), for three reasons:

1. Provide usable feedback for both tbDEX & FTL
2. Useful as a developer integration tool
3. Because it's cool 😎 

---

## What?

- `bin/` initializing FTL dependencies (Hermit & thangs)
- `ftl-module-pfi/` the actual PFI implementation, using FTL
- `integration-sample/` a NodeJS app for development purposes, which acts as "Alice" in the tbDEX flow

---

## Where?

I'm not sure we want to merge this in. I'm sure we'll want this, but I'm not sure we want it here in the `tbdex-pfi-exemplar` code repo. If we yank it out, and place it somewhere else, the only dependency we'll need to duplicate over, is the items under the `db/` directory; otherwise, everything is self contained within the `ftl/` repo.

---

If you want to get your hands dirty, then follow [the README](https://github.com/TBD54566975/tbdex-pfi-exemplar/blob/kendallw/ftl-pfi/ftl/README.md) -- it's crude, but should provide enough to get off-zero.

**[Note]:** if you want to do this prior-to [us cutting a `0.7.0-beta` `tbdex-kt` release](https://discord.com/channels/937858703112155166/949067728709369856/1186381023005655131) then you'll need to `gradle publishToMavenLocal` in [`tbdex-kt`](https://github.com/TBD54566975/tbdex-kt) such that this project can pull from your local JARs.

---

### Current Limitations

- This PFI uses the native FTL HTTP bindings (by using the `@Ingress` feature), but it isn't fully compatible with [the spec](https://github.com/TBD54566975/tbdex/tree/main/specs/http-api). The reason being, we can't currently expose types within FTL interfaces which aren't defined within a `ftl.*` namespace; ergo, what's built in the [`tbdex-kt`'s `protocol` package](https://github.com/TBD54566975/tbdex-kt/tree/main/protocol) can't be used in an FTL verb. So, instead, the current solution is to stringify the data over the HTTP API layer.
  - Notice, [the `integration-sample` NodeJS project](https://github.com/TBD54566975/tbdex-pfi-exemplar/blob/kendallw/ftl-pfi/ftl/integration-sample/index.js). This project is intended to be "Alice" in the tbDEX flow. Notice how we're not currently using [the `@tbdex/http-client` package](https://github.com/TBD54566975/tbdex-js/tree/main/packages/http-client), because the way we're forced to stringify the data over the HTTP API. Instead, we're directly making the `fetch()` HTTP request.
  - For example, [on this line](https://github.com/TBD54566975/tbdex-pfi-exemplar/blob/1ca6ecd92268c386a7ac56a450670867920dac14/ftl/integration-sample/index.js#L19), you'll see something like `const offerings = JSON.parse(body.offerings)` 👉 we're having to parse the stringified JSON within the HTTP body in the client code
  - For this same reason, everything is currently housed within a single FTL Module, instead of broken up into many modules. Because, we use the various [`tbdex-kt`](https://github.com/TBD54566975/tbdex-kt/) and [`web5-kt`](https://github.com/TBD54566975/web5-kt/) types as parameters all over the place, and we can't use those over an FTL `context.call(...)`
  - We have ongoing discussions about how we're going to resolve this with the FTL tech
- DID private keys [are currently hardcoded](https://github.com/TBD54566975/tbdex-pfi-exemplar/blob/kendallw/ftl-pfi/ftl/ftl-module-pfi/src/main/kotlin/ftl/pfi/services/DidService.kt), but who cares, it's a sample 
- Ideally, we use some middleware exposed from the [`tbdex-kt`'s `httpserver` package](https://github.com/TBD54566975/tbdex-kt/tree/main/httpserver) to perform validations... I think there have been some things merged there, but we're not up to date with the latest from that package

---

### Before merging

- [x] We need [to cut a new `tbdex-kt` release (`0.7.0-beta`)](https://discord.com/channels/937858703112155166/949067728709369856/1186381023005655131) and update [the `pom.xml`](https://github.com/TBD54566975/tbdex-pfi-exemplar/blob/1ca6ecd92268c386a7ac56a450670867920dac14/ftl/pom.xml#L48) such that we're pulling tbDEX dependency from the remote, rather than local
- [ ] Decide if we want to house this code in this repo?

### CODE REVIEW

**Review by michaelneale — APPROVED** [review]
I think this is a great idea - still an open question if it should be in separate repo or here, I guess would ask: what mains maintaining it cleaner?

**Comment by KendallWeihe** [comment]
> what ~~mains~~ makes maintaining it cleaner?

Intuitively, I would bet keeping git repos language-specific would be the wise move. Which means, we should have separate `tbdex-pfi-exemplar-js` and `tbdex-pfi-exemplar-ftl` repos.

**Comment by michaelneale** [comment]
@KendallWeihe yeah that is the pattern we use elsewhere

**Comment by michaelneale** [comment]
@KendallWeihe I would almost call this tbdex-pfi-examplar-kt - and make the focus on that? FTL is the "detail" on how to run it perhaps? can that work?

**Comment by KendallWeihe** [comment]
> call this tbdex-pfi-examplar-kt

Yeah totally agree

**Comment by KendallWeihe** [comment]
> had any more thoughts on this @KendallWeihe or should close it/move it?

oops, still lingering

closing for now, can use for reference down the road, thanks!

**Pull request closed without merging**
