### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by michaelneale**

### CODE REVIEW

**Review by mistermoe — COMMENTED** [review]
this dependency can be removed entirely @michaelneale. it's not being used

**Comment by michaelneale** [comment]
will do

**Comment by mistermoe** [comment]
here's updated `package.json`

```json
{
  "name": "tbdex-mock-pfi",
  "type": "module",
  "version": "1.0.0",
  "dependencies": {
    "@tbdex/http-server": "0.18.0",
    "@web5/common": "0.2.1",
    "@web5/crypto": "0.2.1",
    "@web5/dids": "0.2.1",
    "ajv": "8.12.0",
    "dotenv": "16.3.1",
    "express": "4.18.2",
    "kysely": "0.26.3",
    "pg": "8.11.3",
    "loglevel": "1.8.1",
    "loglevel-plugin-prefix": "0.8.4",
    "ms": "2.1.3"
  },
  "devDependencies": {
    "@sphereon/pex-models": "2.1.1",
    "@sphereon/ssi-types": "0.17.5",
    "@types/chai": "4.3.4",
    "@types/eslint": "8.37.0",
    "@types/express": "4.17.17",
    "@types/mocha": "10.0.1",
    "@types/node": "20.9.2",
    "@types/pg": "8.10.2",
    "@types/sinon": "10.0.15",
    "@types/supertest": "2.0.12",
    "@typescript-eslint/eslint-plugin": "6.2.1",
    "@typescript-eslint/parser": "6.2.1",
    "chai": "4.3.10",
    "eslint": "8.46.0",
    "kysely-codegen": "0.11.0",
    "mocha": "10.2.0",
    "rimraf": "5.0.1",
    "sinon": "15.2.0",
    "supertest": "6.3.3",
    "typescript": "5.2.2"
  },
  "scripts": {
    "clean": "rimraf dist",
    "compile": "tsc",
    "lint": "eslint . --ext .ts --max-warnings 0",
    "lint:fix": "eslint . --ext .ts --fix",
    "server": "npm run clean && npm run compile && node --enable-source-maps dist/main.js",
    "test": "rimraf dist/tests && npm run compile && node --test",
    "seed-offerings": "npm run clean && npm run compile && node dist/seed-offerings.js",
    "try": "npm run clean && npm run compile && node --enable-source-maps dist/client-test.js",
    "example-create-issuer": "npm run clean && npm run compile && node --enable-source-maps dist/example/create-issuer.js",
    "example-create-customer": "npm run clean && npm run compile && node --enable-source-maps dist/example/create-customer.js",
    "example-issue-credential": "npm run clean && npm run compile && node --enable-source-maps dist/example/issue-credential.js",
    "example-rfq": "npm run clean && npm run compile && node --enable-source-maps dist/example/request-for-quote.js"
  }
}

```

**Review by mistermoe — COMMENTED** [review]
🏅

**Pull request merged**
