### PR TITLE
adding in stored balances

### PR DESCRIPTION
**Pull request by michaelneale**
adding stored balances support

### CODE REVIEW

**Comment by michaelneale** [comment]
cc @ethan-tbd for review - this doesn't have STORED_BALANCE -> STORED_BALANCE yet as not sure how the "to" did is passed in (from looking at didpay code).

**Comment by ethan-tbd** [comment]
> cc @ethan-tbd for review - this doesn't have STORED_BALANCE -> STORED_BALANCE yet as not sure how the "to" did is passed in (from looking at didpay code).

yea this looks great! we still need to work out the fine details of a `STORED_BALANCE` to `STORED_BALANCE` send offering. i imagine we could use the `to` field in the `Rfq` (instead of putting the pfi's did) and have the recipient did map to one of their pfi dids? not sure yet..

**Comment by michaelneale** [comment]
@ethan-tbd I think the `to` tells the client what PFI to talk to, so can't really be used for send (if its the field I am thinking of anyway).

**Comment by ethan-tbd** [comment]
> @ethan-tbd I think the `to` tells the client what PFI to talk to, so can't really be used for send (if its the field I am thinking of anyway).

actually seems like we would have the `to` be your pfi's did and the recipient's payment address would be passed in via `requiredPaymentDetails` (since the pfi sends on your behalf as they custody your funds)

**Comment by michaelneale** [comment]
@ethan-tbd yes, that is what I was meaning, yeah.

**Pull request merged**
